services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build: ./frontend/todo-app
    ports:
      - :8080:80
    depends_on:
      - backend
